### ISSUE TITLE
Missing description under title

### ISSUE THREAD

**Issue by lfarah** [Zewo/Reflection#1]
<img width="343" alt="screen shot 2016-05-17 at 3 08 55 am" src="https://cloud.githubusercontent.com/assets/6511079/15318811/b5b0c918-1bdc-11e6-8803-0da95083b166.png">
Should be:

> Reflection provides an API for advanced reflection at runtime including dynamic construction of types.

**Comment by antonmes** [comment]
@paulofaria

**Comment by antonmes** [comment]
Fixed, thanks!
