### ISSUE TITLE
Swift 4.1

### ISSUE THREAD

**Issue by robertjpayne** [Zewo/Reflection#13]
Getting some crashes in Swift 4.1 around:

```
    var numberOfFields: Int {
        return Int(pointer.pointee.numberOfFields)
    }
```

in `NominalTypeDescriptor`, trying to dig into what may have changed but I think there was some memory layout changes!

**Comment by yonat** [comment]
Same fo me.

**Comment by bradhilton** [comment]
Okay, I'm taking a look :)

**Comment by bradhilton** [comment]
Okay I just resolved the issue. Thanks for letting me know!
