### ISSUE TITLE
Swift 4.2

### ISSUE THREAD

**Issue by tanner0101** [Zewo/Reflection#14]
The nominal type descriptor metadata is going away completely in 4.2. So there's no longer a way to get field names and types with the method this package uses. There is a new runtime method `swift_getFieldAt` to retrieve this data, however it uses C++ std::function and is not callable from Swift. You'd need to create a C++ wrapper that exposes a C API to use this. I've opened a PR on Swift to fix this (and make the method easily callable from Swift), but I'm not sure if they will do anything about it: https://github.com/apple/swift/pull/15565. Thought I would share this info, thanks for the cool package!

**Comment by bradhilton** [comment]
Thanks a ton @tanner0101, that's good to know. Hopefully they merge your PR. :)

**Comment by bradhilton** [comment]
@tanner0101 This other library also depends on this method of accessing type properties: https://github.com/wickwirew/Runtime

**Comment by tanner0101** [comment]
I'll go ahead and open an issue there, too. :)

**Comment by bradhilton** [comment]
@tanner0101 Swift 4.2 should be supported in the latest on master

**Comment by robertjpayne** [comment]
@bradhilton FYI the silgen trick doesn't work on SwiftLinux anymore more info in https://github.com/wickwirew/Runtime/issues/18
