### ISSUE TITLE
support cocoapods and IOS Project?

### ISSUE THREAD

**Issue by arden** [Zewo/Reflection#2]
this could support cocoapods and IOS Project?

**Comment by antonmes** [comment]
Hi @arden! 

We have no plans for cocoapods because we use Swift 3 + SwiftPM, 
but you can try Xcode 8, which ships with Swift 3 Preview 1.

**Comment by bradhilton** [comment]
@arden, 
Since we're targeting Swift 3, I don't believe we can release this as a public CocoaPod. However, I have another repository that targets Swift 2, https://github.com/bradhilton/Allegro, which does have a CocoaPod. Please let me know if you have any questions, as the APIs are bit different.

**Comment by J7mbo** [comment]
Any plans for putting this on cocoa pods yet?
